version: "3.8"

networks:
  asylum-net:
    driver: bridge

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: asylum_elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - asylum-net

  wazuh.manager:
    image: wazuh/wazuh:4.2.5
    container_name: asylum_wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
    volumes:
      - wazuh-data:/var/ossec/data
    networks:
      - asylum-net

  thehive:
    image: thehiveproject/thehive4:4.0.2
    container_name: asylum_thehive
    depends_on:
      - elasticsearch
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
      - THEHIVE_elasticsearch.cluster-name=hive
      - THEHIVE_elasticsearch.hostname=elasticsearch
      - THEHIVE_elasticsearch.index-prefix=hive
      - THEHIVE_log.console.level=info
    restart: always
    ports:
      - "9000:9000"
    networks:
      - asylum-net

volumes:
  wazuh-data:
  esdata:
