version: '3.7'

services:
  wazuh-manager:
    image: wazuh/wazuh
    environment:
      - WAZUH_MANAGER_PASSWORD=your_wazuh_password
      - WAZUH_API_PASSWORD=your_api_password
    volumes:
      - /opt/asylum/certs:/usr/share/elasticsearch/config/certs  # Certificati TLS
      - asylum_wazuh-data:/var/ossec/data  # Dati di Wazuh
    ports:
      - "55000:55000"
    networks:
      - asylum-net
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=your_elastic_password
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/key.pem
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/cert.pem
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/cert.pem
    volumes:
      - /opt/asylum/certs:/usr/share/elasticsearch/config/certs  # Certificati TLS
      - asylum_elasticsearch-data:/usr/share/elasticsearch/data  # Dati di Elasticsearch
    ports:
      - "9200:9200"
    networks:
      - asylum-net
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  thehive:
    image: thehiveproject/thehive
    environment:
      - THEHIVE_PORT=9000
    volumes:
      - /opt/asylum/certs:/etc/thehive/certs  # Certificati TLS
      - asylum_thehive-data:/data  # Dati di TheHive
    ports:
      - "9000:9000"
    networks:
      - asylum-net
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  asylum_elasticsearch-data:
    driver: local
  asylum_thehive-data:
    driver: local
  asylum_wazuh-data:
    driver: local

networks:
  asylum-net:
    driver: bridge
