version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh:4.2.5
    environment:
      - WAZUH_MANAGER_PASSWORD=SuperSecurePassword1
      - WAZUH_API_PASSWORD=AnotherSecurePassword2
    volumes:
      - wazuh-data:/var/ossec/data
      - /opt/asylum/certs:/certs  # Certificati self-signed
    networks:
      - internal-network
    ports:
      - "1514:1514"    # Porta Wazuh (TCP)
      - "55000:55000"  # Porta API di Wazuh (TCP)
    restart: always
    container_name: asylum_wazuh-manager

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=yourPassword
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/certs/key.pem
      - xpack.security.transport.ssl.certificate=/certs/cert.pem
      - xpack.security.transport.ssl.certificate_authorities=/certs/ca.pem
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/certs/key.pem
      - xpack.security.http.ssl.certificate=/certs/cert.pem
      - xpack.security.http.ssl.certificate_authorities=/certs/ca.pem
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - /opt/asylum/certs:/certs
    networks:
      - internal-network
    ports:
      - "9200:9200"    # HTTPS
      - "9300:9300"    # Nodo transport
    restart: always
    container_name: asylum_elasticsearch

  thehive:
    image: thehiveproject/thehive:latest
    environment:
      - SECRET_KEY=SuperSecretKey
      - DB_HOST=elasticsearch
      - DB_PORT=9200
      - DB_USER=elastic
      - DB_PASSWORD=yourPassword
      - HTTP_SSL_CERTIFICATE=/certs/cert.pem
      - HTTP_SSL_KEY=/certs/key.pem
      - HTTP_LISTENER_ENABLED=true
    volumes:
      - thehive-data:/data
      - /opt/asylum/certs:/certs
    networks:
      - internal-network
    ports:
      - "9000:9000"    # HTTPS
    restart: always
    container_name: asylum_thehive

volumes:
  wazuh-data:
  elasticsearch-data:
  thehive-data:

networks:
  internal-network:
    driver: bridge
