version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh:4.2.5
    network_mode: host  # Usa la rete host per una comunicazione diretta
    environment:
      - WAZUH_MANAGER_PASSWORD=SuperSecurePassword1
      - WAZUH_API_PASSWORD=AnotherSecurePassword2
    volumes:
      - wazuh-data:/var/ossec/data
      - ./certs:/certs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    network_mode: host  # Usa la rete host
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=yourPassword
      - ELASTICSEARCH_SSL_CERTIFICATE=/certs/cert.pem
      - ELASTICSEARCH_SSL_KEY=/certs/key.pem
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/certs

  thehive:
    image: thehiveproject/thehive:latest
    network_mode: host  # Usa la rete host
    environment:
      - SECRET_KEY=SuperSecretKey
      - DB_HOST=localhost
      - DB_PORT=9200
      - DB_USER=elastic
      - DB_PASSWORD=yourPassword
      - HTTP_SSL_CERTIFICATE=/certs/cert.pem
      - HTTP_SSL_KEY=/certs/key.pem
    volumes:
      - thehive-data:/data
      - ./certs:/certs

volumes:
  wazuh-data:
  elasticsearch-data:
  thehive-data:
