version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh:4.2.5
    environment:
      - WAZUH_MANAGER_PASSWORD=SuperSecurePassword1
      - WAZUH_API_PASSWORD=AnotherSecurePassword2
    volumes:
      - wazuh-data:/var/ossec/data
      - /opt/asylum/certs:/certs  # Certificati self-signed
    networks:
      - internal-network
    ports:
      - "1514:1514"    # Porta Wazuh (TCP)
      - "55000:55000"  # Porta API di Wazuh (TCP)
    restart: always
    container_name: asylum_wazuh-manager

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - internal-network
    ports:
      - "9200:9200"    # HTTPS
    restart: always
    container_name: asylum_elasticsearch

  thehive:
    image: thehiveproject/thehive4:4.0.2
    environment:
      - SECRET_KEY=SuperSecretKey
      - DB_HOST=elasticsearch
      - DB_PORT=9200
      - DB_USER=elastic
      - DB_PASSWORD=yourPassword
      - HTTP_LISTENER_ENABLED=true
      - THEHIVE_ADMIN_USER=admin
      - THEHIVE_ADMIN_PASSWORD=admin
    volumes:
      - thehive-data:/data
    networks:
      - internal-network
    ports:
      - "9000:9000"    # HTTPS
    restart: always
    container_name: asylum_thehive

volumes:
  wazuh-data:
  elasticsearch-data:
  thehive-data:

networks:
  internal-network:
    driver: bridge
