version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh:4.2.5
    network_mode: host  # Usa la rete host per connettersi direttamente alla rete
    environment:
      - WAZUH_MANAGER_PASSWORD=SuperSecurePassword1
      - WAZUH_API_PASSWORD=AnotherSecurePassword2
    volumes:
      - wazuh-data:/var/ossec/data  # Persistenza dei dati di Wazuh
      - ./certs:/certs  # Montaggio certificati
    ports:
      - "55000:55000"  # Porta di comunicazione Wazuh
      - "1515:1515/tcp"  # Porta per la comunicazione con l'agente
      - "1514:1514/tcp"  # Porta per il ricevimento degli agenti Wazuh

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    network_mode: host  # Usa la rete host per connettersi direttamente alla rete
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=yourPassword
      - ELASTICSEARCH_SSL_CERTIFICATE=/certs/cert.pem  # Certificato SSL
      - ELASTICSEARCH_SSL_KEY=/certs/key.pem  # Certificato chiave
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./certs:/certs  # Montaggio certificati
    ports:
      - "9200:9200"  # Porta di accesso a Elasticsearch

  thehive:
    image: strangebee/thehive:5.6.0
    network_mode: host  # Usa la rete host per connettersi direttamente alla rete
    environment:
      - SECRET_KEY=SuperSecretKey
      - DB_HOST=localhost
      - DB_PORT=9200
      - DB_USER=elastic
      - DB_PASSWORD=yourPassword
      - HTTP_SSL_CERTIFICATE=/certs/cert.pem  # Certificato SSL per TheHive
      - HTTP_SSL_KEY=/certs/key.pem  # Chiave SSL per TheHive
    volumes:
      - thehive-data:/data
      - ./certs:/certs  # Montaggio certificati
    ports:
      - "9000:9000"  # Porta per accedere a TheHive

volumes:
  wazuh-data:
  elasticsearch-data:
  thehive-data:
