version: '3.8'

services:
  wazuh-manager:
    image: wazuh/wazuh:4.2.5
    network_mode: host  # Usa la rete host per connettersi direttamente alla rete
    environment:
      - WAZUH_MANAGER_PASSWORD=SuperSecurePassword1
      - WAZUH_API_PASSWORD=AnotherSecurePassword2
    volumes:
      - wazuh-data:/var/ossec/data  # Persistenza dei dati di Wazuh
    ports:
      - "55000:55000"  # Porta di comunicazione Wazuh
      - "1515:1515/tcp"  # Porta per la comunicazione con l'agente
      - "1514:1514/tcp"  # Porta per il ricevimento degli agenti Wazuh

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    network_mode: host  # Usa la rete host per connettersi direttamente alla rete
    environment:
      - discovery.type=single-node  # Configurazione per eseguire Elasticsearch in modalità singolo nodo
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data  # Persistenza dei dati di Elasticsearch
    ports:
      - "9200:9200"  # Porta di accesso a Elasticsearch

  thehive:
    image: thehiveproject/thehive:4.2.0
    network_mode: host  # Usa la rete host per connettersi direttamente alla rete
    environment:
      - SECRET_KEY=SuperSecretKey
      - DB_HOST=localhost  # Elasticsearch sarà sulla rete host
      - DB_PORT=9200
      - DB_USER=elastic
      - DB_PASSWORD=yourPassword
    volumes:
      - thehive-data:/data  # Persistenza dei dati di TheHive
    ports:
      - "9000:9000"  # Porta per accedere a TheHive

volumes:
  wazuh-data:
  elasticsearch-data:
  thehive-data:
