NODE_NAME: "node-1"
WAZUH_USER: "admin"
WAZUH_PASS: "admin"
WAZUH_SERVER_IP: "192.168.1.103"
FILEBEAT_DEB: "filebeat-oss-7.10.2-amd64.deb"
GPG_KEY_URL: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
WAZUH_REPO_URL: "https://packages.wazuh.com/4.x/apt/"
WAZUH_CERT_TOOL: "https://packages.wazuh.com/4.11/wazuh-certs-tool.sh"
WAZUH_CERT_CONFIG: "https://packages.wazuh.com/4.11/config.yml"
CERT_ARCHIVE: "/root/wazuh-certificates.tar.gz"